# Generated by Django 4.2.7 on 2023-11-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('lastlogin', models.DateTimeField()),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
    ]
