# Generated by Django 4.2.7 on 2023-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_members_lastlogin_alter_members_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(default='123456', max_length=50),
        ),
    ]
