# Generated by Django 4.2.7 on 2023-11-18 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_members_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='mid',
            field=models.UUIDField(default=uuid.UUID('5fe88065-0776-440b-87ea-ade8f00ed7df'), editable=False, unique=True),
        ),
    ]
