# Generated by Django 4.2.7 on 2023-11-20 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_members_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='mid',
            field=models.UUIDField(default=uuid.UUID('4a31d1ad-ffcc-448f-80b5-0910c82fac77'), editable=False, unique=True),
        ),
    ]
