# Generated by Django 4.2.7 on 2023-11-21 07:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_events_alter_members_mid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='evenetname',
            new_name='eventname',
        ),
        migrations.AlterField(
            model_name='events',
            name='eid',
            field=models.UUIDField(default=uuid.UUID('ea186a8e-3734-45c9-a664-84d3e6887313'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='mid',
            field=models.UUIDField(default=uuid.UUID('d1c2427f-271b-4c69-a791-4cae1f33f295'), editable=False, unique=True),
        ),
    ]
