# Generated by Django 4.2.7 on 2023-11-21 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_evenetname_events_eventname_alter_events_eid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='eid',
            field=models.UUIDField(default=uuid.UUID('04173439-6fc5-47c5-84eb-f5e4263234c6'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='mid',
            field=models.UUIDField(default=uuid.UUID('8e87467f-ff99-4644-8285-f5215ef21dd5'), editable=False, unique=True),
        ),
    ]
