# Generated by Django 4.2.7 on 2023-11-21 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_events_eid_alter_members_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='mid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
